import type { LevelDefinition } from './types';

export const LEVELS: readonly LevelDefinition[] = [
  {
    id: 'first-shift',
    name: 'First Shift',
    sector: 'SECTOR 01 // AWAKENING',
    briefing: 'Extract every Infotron. Steel and Carbon Trusses are permanent; rounded violet walls permit edge rolls.',
    parSeconds: 72,
    map: [
      'XXXX############XXXX',
      'X@....I......W...E.X',
      'X..........O.W.....X',
      '#............W.....#',
      '#....XXXX....W.....#',
      '#....X..X..........#',
      '#..I.X..X....O.....#',
      '#....X..X..........#',
      'X....XXXX......I...X',
      'X..................X',
      'XXXX############XXXX',
    ],
  },
  {
    id: 'circuit-warren',
    name: 'Circuit Warren',
    sector: 'SECTOR 02 // LATERAL SHIFT',
    briefing: 'The network sprawls beyond your optics. Track patrols on the tactical map.',
    parSeconds: 180,
    map: [
      'XXXXX############################XXXXX',
      'X@...................................X',
      'X......I........I........WWWWWWWWWWW.X',
      'X.....O..................W      I  W.X',
      '#..XXXX.####.XXXXX.X.....W         W.#',
      '#..................X......         W.#',
      '#..............O...XWW.WWW I       W.#',
      '#...WW.WW.W..............W    S    W.#',
      '#.........#........#..O..WWWW.WWWW.W.#',
      '#.###.XXX.#........#.XXX.####.XXX.#..#',
      '#.........XXX.###.XX............#....#',
      '#............O.................O#....#',
      '#.WWW.WWW.WW..#...#WW#.##WW#.........#',
      '#.W        W..#...#        #....#.I..#',
      '#.W     D  W..#....  I     W.#..#....#',
      '#.W  I     .......#        #.#W.WWW.W#',
      '#.W        W..#...W      I ..#.......#',
      '#.W     I  W..#.O.#    S   #.........#',
      '#.W   S    W......XXXWW#.XXX.#I......#',
      '#.WW.WWWWWWW..#.........W............#',
      'X.....XXX.#####.XXXXX.XXX...O#.......X',
      'X............I..........W.D..#.......X',
      'X.......................W..........E.X',
      'XXXXX############################XXXXX',
    ],
  },
  {
    id: 'deep-cascade',
    name: 'Deep Cascade',
    sector: 'SECTOR 03 // VERTICAL NULL',
    briefing: 'Breach each deck with Pulse Disks. Control the cascade or be buried by it.',
    parSeconds: 260,
    map: [
      'XXXXX##################################XXXXX',
      'X.@...........X...O..........X.............X',
      'X....I....O...X..........I...X...O.........X',
      'X................D ..........X.........I...X',
      '#......... ...XWWW .WWWWW.WWW.... .........#',
      '#......D.W W..X... ...D......X... ..D......#',
      '#XXX###WXXXX####XXXX##W#XXXX####XXXXW###XXX#',
      '#........X....O........O..#..........X.....#',
      '#..I................I.....#.......O..X...I.#',
      '#........X#### .#####.# ##...........X.....#',
      '#............. ........ ..#...I... ........#',
      '#....D...X...W W.D..... ..#....D.. ..X..D..#',
      '####XWXX####XXXX#W##XXXX####XXXW####XXXXW###',
      '#......X....O...#..........O.....X.........#',
      '#...I..X.....................I...X..O......#',
      '#........... ...#WWW.WWWWWW .WWWWX.........#',
      '#......X.... ...#...I...... ........ ...I..#',
      '#......X..D. .........W.WD. .....X.. .D....#',
      '#XXX####XXWX####XXXX####XWXX####XXXX##W#XXX#',
      '#.......O...X.....I....O....X........O...I.#',
      '#.....I.....X................WWW.WWWWWW.WWW#',
      '####.### ###........... ....X..I..... .....#',
      '#...D... ...X.......D.. ....X.....DWW .....#',
      '####WXXX####XXXX####WXXX####XXXX##W#XXXX####',
      'X..........O...W.......I...O..X............X',
      'X.....I.......................X......I.....X',
      'X.......... ...W........... .............E.X',
      'XXXXX##################################XXXXX',
    ],
  },
];
